# Generated by Django 2.1.2 on 2018-11-03 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, unique=True)),
                ('rel_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Application Releases',
                'ordering': ['-version', '-rel_date'],
            },
        ),
        migrations.CreateModel(
            name='AppType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(help_text='Application branches', max_length=30, unique=True)),
                ('description', models.CharField(blank=True, default='Simply description in less than 100 letters', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Application Types',
            },
        ),
        migrations.CreateModel(
            name='FirmwareRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, unique=True)),
                ('rel_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Firmware Releases',
                'ordering': ['fw_type', '-version', 'rel_date'],
            },
        ),
        migrations.CreateModel(
            name='FirmwareType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(blank=True, help_text='Simply description in less than 100 letters', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Firmware Types',
            },
        ),
        migrations.CreateModel(
            name='SoftwareBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(blank=True, default='Simply description in less than 100 letters', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Software Branches',
            },
        ),
        migrations.CreateModel(
            name='SoftwareRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.CharField(max_length=20, unique=True)),
                ('rel_date', models.DateField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sfxRelease.SoftwareBranch')),
            ],
            options={
                'verbose_name_plural': 'Software Releases',
                'ordering': ['branch', '-revision', '-rel_date'],
            },
        ),
        migrations.AddField(
            model_name='firmwarerelease',
            name='fw_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sfxRelease.FirmwareType'),
        ),
        migrations.AddField(
            model_name='apprelease',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sfxRelease.AppType'),
        ),
    ]
