# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=60)),
                ('body', models.TextField()),
                ('pub_date', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
            ],
        ),
    ]
