# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifoot', '0002_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'user'), (2, 'admin')], default=1),
        ),
    ]
