# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_userinfo_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ('-pub_date',)},
        ),
    ]
