# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-23 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoThisDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('task_date', models.DateField(default=django.utils.timezone.now)),
                ('task_time', models.TimeField(help_text='Time format e.g. : 12:20')),
                ('status', models.CharField(choices=[('Not-Started', 'Not-Started'), ('Ongoing', 'Ongoing'), ('Delayed', 'Delayed'), ('Finished', 'Finished'), ('Canceled', 'Canceled')], default='Not-Started', max_length=20)),
                ('importance', models.CharField(choices=[('High', 'High'), ('Middle', 'Middle'), ('Low', 'Low'), ('General', 'General')], default='General', max_length=10)),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('task_time',),
            },
        ),
        migrations.CreateModel(
            name='TodoThisMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('Not-Started', 'Not-Started'), ('Ongoing', 'Ongoing'), ('Delayed', 'Delayed'), ('Finished', 'Finished'), ('Canceled', 'Canceled')], default='Not-Started', max_length=20)),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('importance', models.CharField(choices=[('High', 'High'), ('Middle', 'Middle'), ('Low', 'Low'), ('General', 'General')], default='General', max_length=10)),
                ('finished', models.DecimalField(decimal_places=0, default='0', help_text='Percentage, from 0 to 100', max_digits=3)),
            ],
            options={
                'ordering': ('start_date',),
            },
        ),
        migrations.CreateModel(
            name='TodoThisYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('Not-Started', 'Not-Started'), ('Ongoing', 'Ongoing'), ('Delayed', 'Delayed'), ('Finished', 'Finished'), ('Canceled', 'Canceled')], default='Not-Started', max_length=20)),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('importance', models.CharField(choices=[('High', 'High'), ('Middle', 'Middle'), ('Low', 'Low'), ('General', 'General')], default='General', max_length=10)),
                ('finished', models.DecimalField(decimal_places=0, default='0', help_text='Percentage, from 0 to 100', max_digits=3)),
            ],
            options={
                'ordering': ('start_date',),
            },
        ),
    ]
