# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 04:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoThisMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('start_day', models.DateField()),
                ('end_day', models.DateField()),
                ('status', models.CharField(choices=[('Not-Started', 'Not-Started'), ('Ongoing', 'Ongoing'), ('Delayed', 'Delayed'), ('Finished', 'Finished'), ('Canceled', 'Canceled')], default='Not-Started', max_length=20)),
                ('create_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('importance', models.CharField(choices=[('High', 'High'), ('Middle', 'Middle'), ('Low', 'Low'), ('General', 'General')], default='General', max_length=10)),
                ('finished', models.DecimalField(decimal_places=0, default='0', help_text='Percentage, from 0 to 100', max_digits=3)),
            ],
            options={
                'ordering': ('start_day',),
            },
        ),
        migrations.AlterModelOptions(
            name='todothisday',
            options={'ordering': ('task_time',)},
        ),
        migrations.RenameField(
            model_name='todothisday',
            old_name='time',
            new_name='task_time',
        ),
        migrations.AddField(
            model_name='todothisday',
            name='task_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
