# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 05:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_auto_20171112_1242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todothismonth',
            options={'ordering': ('start_date',)},
        ),
        migrations.RenameField(
            model_name='todothismonth',
            old_name='end_day',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='todothismonth',
            old_name='start_day',
            new_name='start_date',
        ),
    ]
