# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-18 03:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='moment_app.Category')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='MomentPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('contents', tinymce.models.HTMLField(verbose_name='Content')),
                ('view_num', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField()),
                ('draft', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moment_app.Category')),
            ],
            options={
                'ordering': ('-pub_date',),
                'verbose_name_plural': 'moment-posts',
            },
        ),
    ]
